services:
  # Backend (Node API)
  - type: web
    name: roadmap-server
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node index.js"
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production

  # Frontend (React/Vite)
  - type: web
    name: roadmap-client
    env: node
    rootDir: client
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    plan: starter
    envVars:
      - key: VITE_API_URL
        value: https://roadmap-server.onrender.com
